BINARY_NAME=light-launcher
INSTANCE_BIN=light-launcher-instance
BIN_DIR=bin
DIST_DIR=dist
PROJECT_DIR=src/ui
WAILS_BIN=$(shell go env GOPATH)/bin/wails3

build-all:
	mkdir -p $(BIN_DIR)
	$(MAKE) build-instance
	$(MAKE) build-ui

build-instance:
	cd src && go build -o ../$(BIN_DIR)/$(INSTANCE_BIN) instance/*.go

build-ui:
	cd $(PROJECT_DIR) && PATH="$(shell go env GOPATH)/bin:$(PATH)" $(WAILS_BIN) task build
	cp $(PROJECT_DIR)/bin/$(BINARY_NAME) $(BIN_DIR)/$(BINARY_NAME)

package: build-instance
	cd $(PROJECT_DIR) && PATH="$(shell go env GOPATH)/bin:$(PATH)" $(WAILS_BIN) task package
	cp $(PROJECT_DIR)/bin/light-launcher* $(BIN_DIR)/

build: build-all
	rm -rf $(DIST_DIR)
	mkdir -p $(DIST_DIR)/linux/bin
	mkdir -p $(DIST_DIR)/linux/share/applications
	mkdir -p $(DIST_DIR)/linux/share/icons/hicolor/128x128/apps
	# Binaries
	cp $(BIN_DIR)/$(BINARY_NAME) $(DIST_DIR)/linux/bin/
	cp $(BIN_DIR)/$(INSTANCE_BIN) $(DIST_DIR)/linux/bin/
	# Desktop file (generated by Wails task)
	cp $(PROJECT_DIR)/build/linux/$(BINARY_NAME).desktop $(DIST_DIR)/linux/share/applications/
	# Icon
	cp $(PROJECT_DIR)/build/appicon.png $(DIST_DIR)/linux/share/icons/hicolor/128x128/apps/$(BINARY_NAME).png

generate-bindings:
	cd $(PROJECT_DIR) && PATH="$(shell go env GOPATH)/bin:$(PATH)" $(WAILS_BIN) generate bindings

dev: build-instance
	cd $(PROJECT_DIR) && PATH="$(shell go env GOPATH)/bin:$(PATH)" $(WAILS_BIN) dev

clean:
	rm -rf $(BIN_DIR)
	rm -rf $(DIST_DIR)
	rm -rf $(PROJECT_DIR)/bin
	rm -rf $(PROJECT_DIR)/build/linux/appimage/build
