// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as system$0 from "../system/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

export function CleanupProcesses(): $CancellablePromise<void> {
    return $Call.ByID(342574014);
}

export function ClearShaderCache(): $CancellablePromise<void> {
    return $Call.ByID(3222910385);
}

export function ClearSwap(): $CancellablePromise<void> {
    return $Call.ByID(362406147);
}

export function CloseWindow(): $CancellablePromise<void> {
    return $Call.ByID(1702354253);
}

export function CreatePrefix(name: string): $CancellablePromise<void> {
    return $Call.ByID(898993067, name);
}

export function DetectLosslessDll(): $CancellablePromise<string> {
    return $Call.ByID(3177397130);
}

export function DisableLsfgProfile(profileName: string, gamePath: string): $CancellablePromise<void> {
    return $Call.ByID(2485698212, profileName, gamePath);
}

export function DropCaches(): $CancellablePromise<void> {
    return $Call.ByID(2606425349);
}

export function EditLsfgConfigForGame(mainExecutablePath: string): $CancellablePromise<void> {
    return $Call.ByID(3989122308, mainExecutablePath);
}

export function GetAllGames(): $CancellablePromise<types$0.GameInfo[]> {
    return $Call.ByID(1379387955).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetAppSettings(): $CancellablePromise<types$0.AppSettings | null> {
    return $Call.ByID(1556318213).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetConfig(executablePath: string): $CancellablePromise<types$0.LaunchOptions | null> {
    return $Call.ByID(467323163, executablePath).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetExeIcon(executablePath: string): $CancellablePromise<string> {
    return $Call.ByID(1105188386, executablePath);
}

export function GetImageBase64(imagePath: string): $CancellablePromise<string> {
    return $Call.ByID(3680275921, imagePath);
}

export function GetInitialGamePath(): $CancellablePromise<string> {
    return $Call.ByID(2461105342);
}

export function GetInitialLauncherPath(): $CancellablePromise<string> {
    return $Call.ByID(2024753112);
}

export function GetListGpus(): $CancellablePromise<string[]> {
    return $Call.ByID(2880906562).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetLsfgProfileForGame(name: string, gamePath: string): $CancellablePromise<types$0.LsfgProfileData | null> {
    return $Call.ByID(2364232449, name, gamePath).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetPrefixBaseDir(): $CancellablePromise<string> {
    return $Call.ByID(2747932487);
}

export function GetProtonReleases(variantID: string): $CancellablePromise<system$0.GitHubRelease[]> {
    return $Call.ByID(2398722931, variantID).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetProtonVariants(): $CancellablePromise<system$0.ProtonVariant[]> {
    return $Call.ByID(3819014563).then(($result: any) => {
        return $$createType12($result);
    });
}

export function GetRunningSessions(): $CancellablePromise<types$0.RunningSession[]> {
    return $Call.ByID(907496109).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetShaderCacheSize(): $CancellablePromise<string> {
    return $Call.ByID(1569403559);
}

export function GetShouldEditLsfg(): $CancellablePromise<boolean> {
    return $Call.ByID(169467296);
}

export function GetSystemInfo(): $CancellablePromise<types$0.SystemInfo> {
    return $Call.ByID(2476472468).then(($result: any) => {
        return $$createType15($result);
    });
}

export function GetSystemToolsStatus(): $CancellablePromise<types$0.SystemToolsStatus> {
    return $Call.ByID(3075388133).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetSystemUsage(): $CancellablePromise<types$0.SystemUsage> {
    return $Call.ByID(152950143).then(($result: any) => {
        return $$createType17($result);
    });
}

export function GetTotalRam(): $CancellablePromise<number> {
    return $Call.ByID(4260518999);
}

export function GetUtilsStatus(): $CancellablePromise<types$0.UtilsStatus> {
    return $Call.ByID(1326621324).then(($result: any) => {
        return $$createType18($result);
    });
}

export function InstallLsfg(): $CancellablePromise<void> {
    return $Call.ByID(3353304508);
}

export function InstallProtonVersion(url: string, version: string): $CancellablePromise<void> {
    return $Call.ByID(502735690, url, version);
}

export function KillSession(pid: number): $CancellablePromise<void> {
    return $Call.ByID(161703081, pid);
}

export function ListPrefixes(): $CancellablePromise<string[]> {
    return $Call.ByID(941611035).then(($result: any) => {
        return $$createType6($result);
    });
}

export function LoadPrefixConfig(prefixName: string): $CancellablePromise<types$0.LaunchOptions | null> {
    return $Call.ByID(3624200489, prefixName).then(($result: any) => {
        return $$createType5($result);
    });
}

export function PickFile(): $CancellablePromise<string> {
    return $Call.ByID(1908859236);
}

export function PickFileCustom(title: string, filters: application$0.FileFilter[]): $CancellablePromise<string> {
    return $Call.ByID(1780429503, title, filters);
}

export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(3612359146);
}

export function RemoveGame(executablePath: string): $CancellablePromise<void> {
    return $Call.ByID(530272801, executablePath);
}

export function RemovePrefix(name: string): $CancellablePromise<void> {
    return $Call.ByID(2340120711, name);
}

export function RemoveProfile(mainExecutablePath: string): $CancellablePromise<void> {
    return $Call.ByID(3662052412, mainExecutablePath);
}

export function RestartApp(): $CancellablePromise<void> {
    return $Call.ByID(2246009453);
}

export function RunGame(options: types$0.LaunchOptions, showLogs: boolean): $CancellablePromise<void> {
    return $Call.ByID(2987102522, options, showLogs);
}

export function RunPrefixTool(prefixPath: string, toolName: string, protonPattern: string): $CancellablePromise<void> {
    return $Call.ByID(1601725950, prefixPath, toolName, protonPattern);
}

export function SaveAppSettings(settings: types$0.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(2964614164, settings);
}

export function SaveGameConfig(options: types$0.LaunchOptions): $CancellablePromise<void> {
    return $Call.ByID(3610390934, options);
}

export function SaveLsfgProfile(profileName: string, gamePath: string, multiplier: number, performanceMode: boolean, dllPath: string, gpu: string, flowScale: string, pacing: string, allowFp16: boolean): $CancellablePromise<void> {
    return $Call.ByID(2495706925, profileName, gamePath, multiplier, performanceMode, dllPath, gpu, flowScale, pacing, allowFp16);
}

export function SavePrefixConfig(prefixName: string, options: types$0.LaunchOptions): $CancellablePromise<void> {
    return $Call.ByID(2911285960, prefixName, options);
}

export function ScanProtonVersions(): $CancellablePromise<types$0.ProtonTool[]> {
    return $Call.ByID(3192100603).then(($result: any) => {
        return $$createType20($result);
    });
}

export function SearchExecutables(folderPath: string, maxDepth: number, excludeNames: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(2697676484, folderPath, maxDepth, excludeNames).then(($result: any) => {
        return $$createType6($result);
    });
}

export function Startup(): $CancellablePromise<void> {
    return $Call.ByID(2729254240);
}

export function UninstallLsfg(): $CancellablePromise<void> {
    return $Call.ByID(3511995129);
}

// Private type creation functions
const $$createType0 = types$0.GameInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = types$0.AppSettings.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = types$0.LaunchOptions.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = types$0.LsfgProfileData.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = system$0.GitHubRelease.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = system$0.ProtonVariant.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = types$0.RunningSession.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = types$0.SystemInfo.createFrom;
const $$createType16 = types$0.SystemToolsStatus.createFrom;
const $$createType17 = types$0.SystemUsage.createFrom;
const $$createType18 = types$0.UtilsStatus.createFrom;
const $$createType19 = types$0.ProtonTool.createFrom;
const $$createType20 = $Create.Array($$createType19);
